/** What to tell the player when an action is refused, by the reason code `core/` returns. */

const PROBLEMS: Readonly<Record<string, string>> = {
  biddingOpen: 'Finish the bidding rounds first.',
  biddingEnded: 'The bidding is over for this round.',
  cannotAffordPayroll: 'Your wallet can’t cover the payroll. Release or bench someone.',
  notEnoughGold: 'Not enough gold.',
  breaksBids: 'That would break one of your open bids.',
  belowAsk: 'A bid must be at least the asking price.',
  duplicateBid: 'You already bid on that unit.',
  noPlace: 'No free slot or bench place for that unit.',
  cannotAfford: 'Your bids plus the payroll would be more than your wallet.',
  unknownUnit: 'That unit isn’t available any more.',
  wrongRole: 'MCs go in MC slots, support units in support slots.',
  benchFull: 'The bench is full.',
  noSuchPlace: 'There is no such place.',
  lockedIn: 'You are locked in for this round.',
  unknownCrew: 'Your crew isn’t in this round.',
  noRound: 'No round is open.',
  empty: 'Your crew needs a name.',
  tooLong: 'That name is too long.',
  taken: 'Another crew already has that name.',
  notJson: 'The saved league is damaged and can’t be loaded.',
  notASave: 'The saved data isn’t a Mic Drop League save.',
  newerVersion: 'The saved league is from a newer version of the game.',
  invalid: 'The saved league is damaged and can’t be loaded.',
  unavailable: 'This browser blocks storage, so the league can’t be saved.',
  noPlayer: 'The saved league has no player crew.',
  badCode: 'A room code is four letters.',
  codeTaken: 'No free room code was found. Try again.',
  noSuchRoom: 'No sitting has that room code.',
  timeout: 'The connection timed out. Try again.',
  roomLost: 'The room lost the signalling server; nobody new can join.',
  hostLeft: 'The host left the sitting.',
  protocolMismatch: 'You and the host run different versions of the game. Both reload the page.',
  sittingFull: 'The sitting is full.',
  noAnswer: 'The host didn’t answer. Try again.',
  roundVoided:
    'The host left mid-round, so the round didn’t count. Anyone can host again from the title screen.',
  desync: 'Your game went out of sync with the host’s. It now uses the host’s league.',
  resyncing: 'Your game went out of sync. The host is sending the round again.',
  peerOutOfSync: 'A player’s game was out of sync; it now uses the host’s league.',
  crewTaken: 'Someone at the sitting already plays your crew.',
  roundRunning: 'A round is being played. Try again when it is over.',
  alreadyInLeague: 'You already have a crew in this league.',
  serverUnreachable: 'The signalling server can’t be reached. Check your connection.',
};

export function problemText(reason: string): string {
  return PROBLEMS[reason] ?? `That didn’t work (${reason}).`;
}
